### ISSUE TITLE
Can't install in atom. (Missing github tag?)

### ISSUE THREAD

**Issue by legomind** [blvz/language-livescript-edge#1]
``` bash
Corys-MacBook-Pro:~ cory$ apm install language-livescript-edge
Installing language-livescript-edge to /Users/cory/.atom/packages ✗
Unable to download https://www.atom.io/api/packages/language-livescript-edge/versions/0.1.0/tarball: 404
```

**Comment by blvz** [comment]
Actually, this whole thing was a mess.
It was giving tons of errors and I've put it down, but it seems the `apm` didn't.
But that's okay, I've did it all over again and it seems to be good now. I'm using this fork, take a look: https://github.com/paulmillr/LiveScript.tmbundle/pull/39

There are still some things that doesn't seem to color like they should (or how I'd like them to), so please report any other concerns you might have. Also, test it with different themes, you might get different results.

Thanks.
