### ISSUE TITLE
\text fomatting a bit wierd

### ISSUE THREAD

**Issue by heavyk** [blvz/language-livescript-edge#3]
I switched to your repo from the other livescript one, and I have this issue. have you seen it before?

it doesn't highlight the last letter

<img width="469" alt="screen shot 2015-07-21 at 19 47 52" src="https://cloud.githubusercontent.com/assets/1226324/8808228/9bc9839c-2fe1-11e5-97cc-a0f2f0df55e1.png">

**Comment by blvz** [comment]
Yup. Then I've made a "fix" that actually made things worse. See: 89b77abbdc6abe9e2b39a3588ffdf0037230fbb2 and #2.

But in 1.0.1, with @gabeio's PR, things seem to work fine. See:
![screen shot 2015-07-21 at 8 36 34 pm](https://cloud.githubusercontent.com/assets/134438/8814871/3da55b72-2fe8-11e5-91b8-d6cd469feefe.png)

Maybe it's an issue with the themes? I'm using One Dark for both. Can you please check it?

**Comment by heavyk** [comment]
yes, I see you've made an update. I will look. it appears I made the issue about 15 mins after your update..

get back to you in a moment :) cheers

**Comment by heavyk** [comment]
well the good news is it appears to be the theme. the bad news is, I like my theme a lot.

I'm using "Duotone Dark"

**Comment by heavyk** [comment]
so it appears that it's the same with both themes...

with one dark:
<img width="754" alt="screen shot 2015-07-22 at 02 23 22" src="https://cloud.githubusercontent.com/assets/1226324/8815396/de8330e8-3018-11e5-9681-5dc945176499.png">

with duotone dark
<img width="794" alt="screen shot 2015-07-22 at 02 23 51" src="https://cloud.githubusercontent.com/assets/1226324/8815400/eea546f0-3018-11e5-8db7-1349f118e273.png">

**Comment by gabeio** [comment]
oh yeah that was the issue but I'm ~99% sure it was there prior to 1.0.1 :cry:, I'll see if I can figure that one out too :smiley:...

**Comment by gabeio** [comment]
I forgot that was the issue because I actually hat that backslash feature LOL it's hurt me more than help so I stopped using it...

**Comment by gabeio** [comment]
WOW I forgot how horrible this regex they use is it's not like any other regex >.> it's so WEIRD...

**Comment by heavyk** [comment]
backslash the best feature ever! what are you talking about... lol

for work, I write in normal javascript. I'm tellin ya, it's always a pleasure to get back to livescript and not have to put quotes everywhere.

LOLz yeah, I had a look and decided it was too insane, so I'm trying to temporary fix it rigth now in styles.less

**Comment by gabeio** [comment]
@blvz @heavyk actually I think that is correct... I think the issue is the theme is too old/livescript doesn't technically have an ending punctuation... so the theme is thinking `"asdf"` but because we write it `\asdf` `f` it thinks is `"`... which works with normal javascript and most other languages...

---

you may have to mod the theme just for livescript ROFL

---

I am going to keep looking into this I really can't believe atom doesn't have a way to say there is technically no ending punctuation to something...

**Comment by heavyk** [comment]
I'm looking at the regex right now and I see the problem.

the regex assumes it's a string. it needs quotes to be seen that way...
<img width="638" alt="screen shot 2015-07-22 at 02 54 59" src="https://cloud.githubusercontent.com/assets/1226324/8815705/2a525ed2-301d-11e5-81e5-eb4059390a08.png">

see how the string begin and end are the quote marks? this will need to be something like a keyword instead...

**Comment by blvz** [comment]
@heavyk @gabeio I can't test it right now, but does Duotone have different colors for quotes? If so, I don't think there's a problem with the regex.

And I don't know if you know, but regexes in Atom/tmbundles are [Oniguruma](http://www.geocities.jp/kosako3/oniguruma/doc/RE.txt) based. Knowing that, makes things slightly less painful.

**Comment by gabeio** [comment]
yeah it does have different color quotes... but I am trying to see if there is a way to tell atom that is just the end of the string and not a quote...

**Comment by heavyk** [comment]
maybe something like this will work...

```
{
    match: "\\\\([\\\\)\\s,\\};\\]])?(?!$)[\\w-]*"
    name: "string.quoted.single.livescript"
  }
```

I tried it, but I don't know how to get the editor to update the parser... gonna read atom dev shit real quick. first time doing this

**Comment by gabeio** [comment]
ctrl+alt+cmd+L refreshes the "browser"

**Comment by heavyk** [comment]
NAILED IT!
<img width="602" alt="screen shot 2015-07-22 at 03 06 38" src="https://cloud.githubusercontent.com/assets/1226324/8815812/bdc61504-301e-11e5-85eb-542f864890b1.png">

**Comment by gabeio** [comment]
nice! pr :+1: :smile:

**Comment by heavyk** [comment]
it's the pattern I said above. I also had to start in "dev mode" apparently 

cheers guys!!!

@gabeio have a look at the pattern because I don't think it's 100%

**Comment by heavyk** [comment]
I just don't know much about regex to follow along well. some of these regex hurt my head. gonna try a few things like like terminating backslash (in the other issue) and stuff before I make a pr

**Comment by blvz** [comment]
@heavyk Awesome! I was skeptical about it. 👏👏👏

Looking at the inspector, things seem okay. Does it work on both themes?

Submit a PR for us to test it too. Then  you can add changes if need it. 👍

**Comment by heavyk** [comment]
it does indeed work in both :) put up a PR in a sec. give me a moment

btw I discovered another bug...

<img width="531" alt="screen shot 2015-07-22 at 03 14 14" src="https://cloud.githubusercontent.com/assets/1226324/8815923/3567707a-3020-11e5-8b3f-f9d2b98ff857.png">

look at the `(` after `log`. see how it's not a round brace?

**Comment by gabeio** [comment]
lol wth I think I see another issue LOL notice the left `(` isn't getting marked...

**Comment by heavyk** [comment]
yeah :) you wanna take that one? lol

**Comment by gabeio** [comment]
lol my head still hurts from the first one & you fixed it so fast ;]

**Comment by blvz** [comment]
@heavyk Nice!

Well, as you find bugs, just open issues and when some of us get the time, we fix them. Or at least they are publicly known. I'll give it a shot when I get home, in about an hour.

**Comment by heavyk** [comment]
alright, I'll have a look at it tomorrow. this is kinda fun...

--- btw is there like a special procedure to forking in atom or is it the same thing: fork, clone, npm i, hack, git add remote, push ???

I'm still new to atom (a week now) so this is fun. I'm gonna just paste the change in github right now then I'll read up on it tomorrow. I'm going to bed here soon. it's 3:30 here

**Comment by heavyk** [comment]
done. I'm VERY satisfied with the result. turned out to be easier than I imagined.

https://github.com/blvz/language-livescript-edge/pull/4

cheers guys. looking forward to do this again :)

good night

**Comment by blvz** [comment]
@heavyk it's basically that, but you can use `apm` to make things a little easier. Check the 3rd and 5th comments, here: https://discuss.atom.io/t/load-developing-package/2554

**Comment by heavyk** [comment]
oh that is very helpful! thank you... I'm really liking atom more and more. they advertized "a hackable editor" and I kinda balked at that but honestly I haven't opened sublime since atom.

likely you will see more contributions from me. this is amazing. btw, I was looking at the api: using decorations and markers, I think we could potentially use the LS AST to do perfect highlighting. I'm gonna let that idea swim around in my head a bit first, but I like the sound of it :)

cheers
